language: node_js
node_js:
  - "node"

cache:
  npm: true
  directories:
    - src/assets/generated

script:
  - npm run generate-sqip
  - npm run upload
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
